
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo
type: Opaque
stringData:
  # These are the initial superuser credentials
  ME_CONFIG_MONGODB_ADMINUSERNAME: longbui 
  ME_CONFIG_MONGODB_ADMINPASSWORD: longbui
  MONGO_INITDB_ROOT_USERNAME: longbui
  MONGO_INITDB_ROOT_PASSWORD: longbui