apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhello-deployment
  namespace: nginxhello
  labels:
    app: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginxhello-service
  namespace: nginxhello
spec:
  selector:
    app: nginx-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxhello-ingress
  namespace: nginxhello
spec:
  rules:
  - host: nginx-hello.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxhello-service
            port:
              number: 80
